List users = [
  {
    "id": "1",
    "name": "Alice Johnson",
    "email": "alice@example.com",
    "password": "Alice@123",
    "phone": "1234567890",
    "gender": "female",
    "birthdate": "01/01/1990",
    "age": "33",
    "height": "5'5 ft",
    "weight": "55 kg",
    "hobbies": "Reading 📚, Travel 🌍",
    "education": "Bachelor's Degree",
    "occupation": "Teacher",
    "employed_in": "Government",
    "income": "Less than ₹3,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "English",
    "religion": "Christianity ✝️",
    "country": "USA",
    "state": "California",
    "city": "Los Angeles",
    "is_favorite": 0
  },
  {
    "id": "2",
    "name": "Ravi Patel",
    "email": "ravi.patel@example.com",
    "password": "Ravi@123",
    "phone": "9876543210",
    "gender": "male",
    "birthdate": "15/05/1988",
    "age": "35",
    "height": "5'8 ft",
    "weight": "70 kg",
    "hobbies": "Music 🎵, Sports ⚽",
    "education": "Master's Degree",
    "occupation": "Software Engineer",
    "employed_in": "Private Sector",
    "income": "₹6,00,000 - ₹12,00,000",
    "marital_status": "Married",
    "mother_tongue": "Gujarati",
    "religion": "Hinduism 🕉️",
    "country": "India",
    "state": "Gujarat",
    "city": "Ahmedabad",
    "is_favorite": 1
  },
  {
    "id": "3",
    "name": "Fatima Khan",
    "email": "fatima.khan@example.com",
    "password": "Fatima@123",
    "phone": "8765432109",
    "gender": "female",
    "birthdate": "10/09/1992",
    "age": "31",
    "height": "5'3 ft",
    "weight": "58 kg",
    "hobbies": "Cooking 🍳, Art 🎨",
    "education": "Bachelor's Degree",
    "occupation": "Business Owner",
    "employed_in": "Self-Employed",
    "income": "Above ₹12,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "Urdu",
    "religion": "Islam ☪️",
    "country": "India",
    "state": "Maharashtra",
    "city": "Mumbai",
    "is_favorite": 0
  },
  {
    "id": "4",
    "name": "John Smith",
    "email": "johnsmith@example.com",
    "password": "John@123",
    "phone": "7654321098",
    "gender": "male",
    "birthdate": "25/12/1985",
    "age": "38",
    "height": "6'0 ft",
    "weight": "80 kg",
    "hobbies": "Fitness 🏋️, Movies 🎬",
    "education": "Doctorate",
    "occupation": "Doctor",
    "employed_in": "Government",
    "income": "Above ₹12,00,000",
    "marital_status": "Married",
    "mother_tongue": "English",
    "religion": "Christianity ✝️",
    "country": "Canada",
    "state": "Ontario",
    "city": "Toronto",
    "is_favorite": 1
  },
  {
    "id": "5",
    "name": "Priya Sharma",
    "email": "priya.sharma@example.com",
    "password": "Priya@123",
    "phone": "6543210987",
    "gender": "female",
    "birthdate": "05/07/1995",
    "age": "28",
    "height": "5'4 ft",
    "weight": "52 kg",
    "hobbies": "Dancing 💃, Photography 📸",
    "education": "Master's Degree",
    "occupation": "Freelancer",
    "employed_in": "Self-Employed",
    "income": "₹3,00,000 - ₹6,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "Hindi",
    "religion": "Hinduism 🕉️",
    "country": "India",
    "state": "Uttar Pradesh",
    "city": "Ayodhya",
    "is_favorite": 0
  },
  {
    "id": "6",
    "name": "Carlos Fernandez",
    "email": "carlos@example.com",
    "password": "Carlos@123",
    "phone": "5432109876",
    "gender": "male",
    "birthdate": "20/11/1993",
    "age": "30",
    "height": "5'9 ft",
    "weight": "75 kg",
    "hobbies": "Hiking 🥾, Cycling 🚴",
    "education": "Bachelor's Degree",
    "occupation": "Artist",
    "employed_in": "Private Sector",
    "income": "₹6,00,000 - ₹12,00,000",
    "marital_status": "Divorced",
    "mother_tongue": "English",
    "religion": "Atheism 🚫",
    "country": "USA",
    "state": "New York",
    "city": "New York City",
    "is_favorite": 1
  },
  {
    "id": "7",
    "name": "Emily White",
    "email": "emily.white@example.com",
    "password": "Emily@123",
    "phone": "4321098765",
    "gender": "female",
    "birthdate": "08/06/1997",
    "age": "26",
    "height": "5'6 ft",
    "weight": "60 kg",
    "hobbies": "Fashion 👗, Meditation 🧘",
    "education": "High School",
    "occupation": "Other",
    "employed_in": "Unemployed",
    "income": "Less than ₹3,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "English",
    "religion": "Spiritual but not religious 🛐",
    "country": "Canada",
    "state": "British Columbia",
    "city": "Vancouver",
    "is_favorite": 0
  },
  {
    "id": "8",
    "name": "Amit Verma",
    "email": "amit.verma@example.com",
    "password": "Amit@123",
    "phone": "3210987654",
    "gender": "male",
    "birthdate": "12/04/1980",
    "age": "44",
    "height": "5'7 ft",
    "weight": "68 kg",
    "hobbies": "Poetry 📜, Science 🔬",
    "education": "Doctorate",
    "occupation": "Professor",
    "employed_in": "Government",
    "income": "Above ₹12,00,000",
    "marital_status": "Married",
    "mother_tongue": "Hindi",
    "religion": "Hinduism 🕉️",
    "country": "India",
    "state": "Maharashtra",
    "city": "Pune",
    "is_favorite": 1
  },
  {
    "id": "9",
    "name": "Sophia Martinez",
    "email": "sophia.m@example.com",
    "password": "Sophia@123",
    "phone": "2109876543",
    "gender": "female",
    "birthdate": "03/03/1994",
    "age": "30",
    "height": "5'3 ft",
    "weight": "50 kg",
    "hobbies": "Camping 🏕️, Writing ✍️",
    "education": "Bachelor's Degree",
    "occupation": "Writer",
    "employed_in": "Self-Employed",
    "income": "₹6,00,000 - ₹12,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "Spanish",
    "religion": "Catholicism ✝️",
    "country": "USA",
    "state": "California",
    "city": "San Francisco",
    "is_favorite": 0
  },
  {
    "id": "10",
    "name": "Mohammed Ali",
    "email": "mohammed.ali@example.com",
    "password": "Mohammed@123",
    "phone": "1987654321",
    "gender": "male",
    "birthdate": "10/12/1987",
    "age": "37",
    "height": "5'10 ft",
    "weight": "77 kg",
    "hobbies": "Fishing 🎣, Running 🏃",
    "education": "Master's Degree",
    "occupation": "Doctor",
    "employed_in": "Government",
    "income": "Above ₹12,00,000",
    "marital_status": "Married",
    "mother_tongue": "Urdu",
    "religion": "Islam ☪️",
    "country": "India",
    "state": "Uttar Pradesh",
    "city": "Prayagraj",
    "is_favorite": 1
  },
  {
    "id": "11",
    "name": "Lily Brown",
    "email": "lily.b@example.com",
    "password": "Lily@123",
    "phone": "8765432101",
    "gender": "female",
    "birthdate": "18/09/1998",
    "age": "25",
    "height": "5'2 ft",
    "weight": "48 kg",
    "hobbies": "Technology 💻, Art 🎨",
    "education": "Bachelor's Degree",
    "occupation": "Graphic Designer",
    "employed_in": "Private Sector",
    "income": "₹3,00,000 - ₹6,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "English",
    "religion": "Christianity ✝️",
    "country": "Canada",
    "state": "Quebec",
    "city": "Montreal",
    "is_favorite": 0
  },
  {
    "id": "12",
    "name": "Rajesh Mehta",
    "email": "rajesh.mehta@example.com",
    "password": "Rajesh@123",
    "phone": "7654321092",
    "gender": "male",
    "birthdate": "25/01/1982",
    "age": "42",
    "height": "6'1 ft",
    "weight": "82 kg",
    "hobbies": "Motor Sports 🏎️, Running 🏃",
    "education": "Bachelor's Degree",
    "occupation": "Business Owner",
    "employed_in": "Self-Employed",
    "income": "Above ₹12,00,000",
    "marital_status": "Married",
    "mother_tongue": "Gujarati",
    "religion": "Hinduism 🕉️",
    "country": "India",
    "state": "Gujarat",
    "city": "Vadodara",
    "is_favorite": 1
  },
  {
    "id": "13",
    "name": "Aisha Begum",
    "email": "aisha.b@example.com",
    "password": "Aisha@123",
    "phone": "6543210983",
    "gender": "female",
    "birthdate": "15/04/1993",
    "age": "31",
    "height": "5'1 ft",
    "weight": "55 kg",
    "hobbies": "Meditation 🧘, Poetry 📜",
    "education": "Master's Degree",
    "occupation": "Professor",
    "employed_in": "Government",
    "income": "₹6,00,000 - ₹12,00,000",
    "marital_status": "Married",
    "mother_tongue": "Hindi",
    "religion": "Islam ☪️",
    "country": "India",
    "state": "Maharashtra",
    "city": "Nagpur",
    "is_favorite": 0
  },
  {
    "id": "14",
    "name": "Daniel Green",
    "email": "daniel.green@example.com",
    "password": "Daniel@123",
    "phone": "5432109874",
    "gender": "male",
    "birthdate": "30/06/1989",
    "age": "35",
    "height": "5'11 ft",
    "weight": "78 kg",
    "hobbies": "Gaming 🎮, Science 🔬",
    "education": "Bachelor's Degree",
    "occupation": "Software Engineer",
    "employed_in": "Private Sector",
    "income": "₹6,00,000 - ₹12,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "English",
    "religion": "Atheism 🚫",
    "country": "Canada",
    "state": "Ontario",
    "city": "Ottawa",
    "is_favorite": 1
  },
  {
    "id": "15",
    "name": "Sneha Kapoor",
    "email": "sneha.kapoor@example.com",
    "password": "Sneha@123",
    "phone": "4321098763",
    "gender": "female",
    "birthdate": "12/08/1996",
    "age": "27",
    "height": "5'4 ft",
    "weight": "53 kg",
    "hobbies": "Interior Design 🏡, Cooking 🍳",
    "education": "Bachelor's Degree",
    "occupation": "Architect",
    "employed_in": "Private Sector",
    "income": "₹3,00,000 - ₹6,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "Punjabi",
    "religion": "Sikhism 🪯",
    "country": "India",
    "state": "Punjab",
    "city": "Ludhiana",
    "is_favorite": 0
  },
  {
    "id": "16",
    "name": "Chris Johnson",
    "email": "chris.j@example.com",
    "password": "Chris@123",
    "phone": "3210987652",
    "gender": "male",
    "birthdate": "22/07/1991",
    "age": "32",
    "height": "6'2 ft",
    "weight": "85 kg",
    "hobbies": "Nature 🌿, Fashion 👗",
    "education": "Master's Degree",
    "occupation": "Entrepreneur",
    "employed_in": "Self-Employed",
    "income": "Above ₹12,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "English",
    "religion": "Spiritual but not religious 🛐",
    "country": "USA",
    "state": "Texas",
    "city": "Houston",
    "is_favorite": 1
  },
  {
    "id": "17",
    "name": "Ananya Iyer",
    "email": "ananya.iyer@example.com",
    "password": "Ananya@123",
    "phone": "2109876542",
    "gender": "female",
    "birthdate": "14/02/1992",
    "age": "32",
    "height": "5'3 ft",
    "weight": "54 kg",
    "hobbies": "Reading 📚, Science 🔬",
    "education": "Master's Degree",
    "occupation": "Research Scientist",
    "employed_in": "Government",
    "income": "₹6,00,000 - ₹12,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "Tamil",
    "religion": "Hinduism 🕉️",
    "country": "India",
    "state": "Tamil Nadu",
    "city": "Chennai",
    "is_favorite": 0
  },
  {
    "id": "18",
    "name": "Omar Hassan",
    "email": "omar.hassan@example.com",
    "password": "Omar@123",
    "phone": "1987654322",
    "gender": "male",
    "birthdate": "05/05/1985",
    "age": "39",
    "height": "5'10 ft",
    "weight": "79 kg",
    "hobbies": "Travel 🌍, Photography 📸",
    "education": "Bachelor's Degree",
    "occupation": "Journalist",
    "employed_in": "Private Sector",
    "income": "₹3,00,000 - ₹6,00,000",
    "marital_status": "Married",
    "mother_tongue": "Arabic",
    "religion": "Islam ☪️",
    "country": "UAE",
    "state": "Dubai",
    "city": "Dubai",
    "is_favorite": 1
  },
  {
    "id": "19",
    "name": "Jessica Wang",
    "email": "jessica.wang@example.com",
    "password": "Jessica@123",
    "phone": "8765432103",
    "gender": "female",
    "birthdate": "10/11/1990",
    "age": "33",
    "height": "5'5 ft",
    "weight": "57 kg",
    "hobbies": "Music 🎵, Meditation 🧘",
    "education": "Doctorate",
    "occupation": "Psychologist",
    "employed_in": "Self-Employed",
    "income": "Above ₹12,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "Mandarin",
    "religion": "Buddhism ☸️",
    "country": "USA",
    "state": "New York",
    "city": "New York City",
    "is_favorite": 0
  },
  {
    "id": "20",
    "name": "Vikram Singh",
    "email": "vikram.singh@example.com",
    "password": "Vikram@123",
    "phone": "7654321094",
    "gender": "male",
    "birthdate": "20/08/1988",
    "age": "36",
    "height": "5'9 ft",
    "weight": "76 kg",
    "hobbies": "Fitness 🏋️, Motor Sports 🏎️",
    "education": "Bachelor's Degree",
    "occupation": "Mechanical Engineer",
    "employed_in": "Private Sector",
    "income": "₹6,00,000 - ₹12,00,000",
    "marital_status": "Never Married",
    "mother_tongue": "Hindi",
    "religion": "Sikhism 🪯",
    "country": "India",
    "state": "Punjab",
    "city": "Amritsar",
    "is_favorite": 1
  }
];
